begin;
select plan(7);
select tests.create_user('coach@test.dev','Coach'); select tests.create_user('p1@test.dev','P1');
select tests.login_as('coach@test.dev'); select create_club('Club');
insert into paddlers (club_id, name, email, weight_kg, gender) values (auth_club_id(), 'P One', 'p1@test.dev', 61.5, 'female');
insert into erg_tests (paddler_id, metres, source, tested_at) select id, 500, 'coach', '2026-01-01' from paddlers;
insert into erg_tests (paddler_id, metres, source, tested_at) select id, 540, 'coach', '2026-03-01' from paddlers;
select is((select erg_m from paddlers_with_power where name='P One'), 540, 'latest erg wins');
select is((select erg_tested_at from paddlers_with_power where name='P One'), '2026-03-01'::date, 'latest date exposed');
select tests.logout();
create temp table invite as select invite_code as code from clubs;
grant select on invite to authenticated;
select tests.login_as('p1@test.dev'); select join_club((select code from invite));
select is((select count(*) from paddlers_with_power), 1::bigint, 'security_invoker view only shows own row to paddler');
select hasnt_column('paddlers_public', 'weight_kg', 'public view hides weight');
select hasnt_column('paddlers_public', 'gender', 'public view hides gender');
select hasnt_column('paddlers_public', 'email', 'public view hides email');
select throws_ok($$ update paddlers_public set name = 'HACKED' where name = 'P One' $$, '42501', null, 'paddlers_public is read-only: no write privilege for authenticated');
select tests.logout();
select * from finish();
rollback;
